export const USDTABI = [
  "function name() view returns (string)",
  "function deprecate(address _upgradedAddress)",
  "function approve(address _spender, uint256 _value)",
  "function deprecated() view returns (bool)",
  "function addBlackList(address _evilUser)",
  "function totalSupply() view returns (uint256)",
  "function transferFrom(address _from, address _to, uint256 _value)",
  "function upgradedAddress() view returns (address)",
  "function balances(address) view returns (uint256)",
  "function decimals() view returns (uint256)",
  "function maximumFee() view returns (uint256)",
  "function _totalSupply() view returns (uint256)",
  "function unpause()",
  "function getBlackListStatus(address _maker) view returns (bool)",
  "function allowed(address, address) view returns (uint256)",
  "function paused() view returns (bool)",
  "function balanceOf(address who) view returns (uint256)",
  "function pause()",
  "function getOwner() view returns (address)",
  "function owner() view returns (address)",
  "function symbol() view returns (string)",
  "function transfer(address _to, uint256 _value)",
  "function setParams(uint256 newBasisPoints, uint256 newMaxFee)",
  "function issue(uint256 amount)",
  "function redeem(uint256 amount)",
  "function allowance(address _owner, address _spender) view returns (uint256 remaining)",
  "function basisPointsRate() view returns (uint256)",
  "function isBlackListed(address) view returns (bool)",
  "function removeBlackList(address _clearedUser)",
  "function MAX_UINT() view returns (uint256)",
  "function transferOwnership(address newOwner)",
  "function destroyBlackFunds(address _blackListedUser)",
  "constructor(uint256 _initialSupply, string _name, string _symbol, uint256 _decimals)",
  "event Issue(uint256 amount)",
  "event Redeem(uint256 amount)",
  "event Deprecate(address newAddress)",
  "event Params(uint256 feeBasisPoints, uint256 maxFee)",
  "event DestroyedBlackFunds(address _blackListedUser, uint256 _balance)",
  "event AddedBlackList(address _user)",
  "event RemovedBlackList(address _user)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Pause()",
  "event Unpause()"
]